version: '3'

services:

  db:
    image: mysql
    container_name: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdemo
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin 
    links:
      - db
    ports:
      - 8081:80

  flaskdemo:
    image: flaskdemo
    container_name: flaskdemo
    ports:
      - "5000:5000"

